### PR TITLE
random-btn-and-ui

### PR DESCRIPTION
**Pull request by Adarwall**
Added a random user button.
Changed the style and colors of the site.

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@Adarwall it seems like a lot of changes, can you link a Screenshot of what you have changed?

**Comment by Adarwall** [comment]
@Ishaan28malik sure, I'm away from my computer at the moment so I'll link the screenshots tommorow 👍

**Comment by pandurijal** [comment]
I think it's because of the node_modules. To avoid this kind of condition, I suggest you put src/node_modules inside .gitignore so it will be ignored when push into your repo..

**Comment by Adarwall** [comment]
@pandurijal I excluded the node_modules thats the main reason for the many changes

**Comment by adin234** [comment]
> @pandurijal I excluded the node_modules thats the main reason for the many changes

the repository owner doesn't like `node_modules` and `build` to be excluded. such a shame

**Comment by adin234** [comment]
hey @Ishaan28malik why are you deleting my comment? its not right to exclude `node_modules` and `build` right?

**Comment by Ishaan28malik** [comment]
@adin234  yes but you are not supposed to talk such things or mention them here . 
@Adarwall can you make a new PR without changing the dependencies or packages .
Just update the UI changes that you were doing previously.
I am closing this one , So that @Adarwall you can start with a fresh.

**Pull request closed without merging**
